package com.getrepo.data

import com.getrepo.data.source.local.entity.RepositoryEntity
import com.getrepo.data.source.remote.dto.ItemResponse
import com.getrepo.data.source.remote.dto.OwnerResponse
import com.getrepo.data.source.remote.dto.RepositoryResponse

val getRepositoriesResponsePageOne = RepositoryResponse(
    1,
    false,
    listOf(
        ItemResponse(
            1,
            "",
            OwnerResponse(
                "",
                ""
            ),
            1,
            1
        ),
        ItemResponse(
            2,
            "",
            OwnerResponse(
                "",
                ""
            ),
            1,
            1
        ),
        ItemResponse(
            3,
            "",
            OwnerResponse(
                "",
                ""
            ),
            1,
            1
        ),
    )
)

val getRepositoriesResponsePageTwo = RepositoryResponse(
    1,
    false,
    listOf(
        ItemResponse(
            4,
            "",
            OwnerResponse(
                "",
                ""
            ),
            1,
            1
        ),
        ItemResponse(
            5,
            "",
            OwnerResponse(
                "",
                ""
            ),
            1,
            1
        ),
        ItemResponse(
            6,
            "",
            OwnerResponse(
                "",
                ""
            ),
            1,
            1
        ),
    )
)

val repositoriesEntityPageOne = listOf<RepositoryEntity>(
    RepositoryEntity(
        1,
        "",
        "",
        "",
        1,
        1,
        1
    ),
    RepositoryEntity(
        2,
        "",
        "",
        "",
        1,
        1,
        1
    ),
    RepositoryEntity(
        3,
        "",
        "",
        "",
        1,
        1,
        1
    )
)

val repositoriesEntityPageTwo = listOf<RepositoryEntity>(
    RepositoryEntity(
        4,
        "",
        "",
        "",
        1,
        1,
        2
    ),
    RepositoryEntity(
        5,
        "",
        "",
        "",
        1,
        1,
        2
    ),
    RepositoryEntity(
        6,
        "",
        "",
        "",
        1,
        1,
        2
    ),
)

val getRepositoriesResponseMax = RepositoryResponse(
    1,
    false,
    listOf(
        ItemResponse(
            1,
            "",
            OwnerResponse(
                "",
                ""
            ),
            1,
            1
        ),
        ItemResponse(
            2,
            "",
            OwnerResponse(
                "",
                ""
            ),
            1,
            1
        ),
        ItemResponse(
            3,
            "",
            OwnerResponse(
                "",
                ""
            ),
            1,
            1
        ),
        ItemResponse(
            4,
            "",
            OwnerResponse(
                "",
                ""
            ),
            1,
            1
        ),
    )
)

val repositoriesEntityPageMax = listOf<RepositoryEntity>(
    RepositoryEntity(
        1,
        "",
        "",
        "",
        1,
        1,
        1
    ),
    RepositoryEntity(
        2,
        "",
        "",
        "",
        1,
        1,
        1
    ),
    RepositoryEntity(
        3,
        "",
        "",
        "",
        1,
        1,
        1
    ),
    RepositoryEntity(
        4,
        "",
        "",
        "",
        1,
        1,
        1
    )
)