//package com.getrepo
//
//import com.getrepo.data.source.remote.dto.ItemResponse
//import com.getrepo.data.source.remote.dto.OwnerResponse
//import com.getrepo.data.source.remote.dto.RepositoryResponse
//
//val getRepositoriesResponse = RepositoryResponse(
//    1,
//    false,
//    listOf(
//        ItemResponse(
//            1,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            2,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            3,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            4,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            5,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            6,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            7,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            8,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            9,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            10,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            11,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            12,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            13,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            14,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            15,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            16,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            17,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            18,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            19,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            20,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        )
//    )
//)
//
//val getRepositoriesResponsePage2 = RepositoryResponse(
//    1,
//    false,
//    listOf(
//        ItemResponse(
//            1,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            2,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            3,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            4,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            5,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            6,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            7,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            8,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            9,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            10,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            11,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            12,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            13,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            14,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            15,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            16,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            17,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            18,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            19,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        ),
//        ItemResponse(
//            20,
//            "",
//            OwnerResponse(
//                "",
//                ""
//            ),
//            1,
//            1
//        )
//    )
//)